### PR TITLE
Add support for NixOS AMIs on AWS

### PR DESCRIPTION
**Pull request by knl**
Essentially, a copy of `google_image_nixos` with modifications to support AWS.

### CODE REVIEW

**Comment by zimbatm** [comment]
thanks @knl, looks good to me!

**Comment by PierreR** [comment]
I can make it work ... I have got this error:
```
Error: resource 'aws_instance.example' config: "self_link" is not a valid output for module "nixos_image_1809"
```

**Comment by zimbatm** [comment]
@knl did you test the code?

**Comment by knl** [comment]
I botched the example in the readme, it was a copy/pasta failure. There is no `self_link`, it should be `ami`. @PierreR which error do you get with using region?

**Comment by zimbatm** [comment]
@knl do you mind sending a PR to fix the example?

**Comment by knl** [comment]
@zimbatm There is now a new PR that fixes the example: #5 . Sorry for a belated response, family upgrades were in process :)

**Comment by zimbatm** [comment]
no worries, thanks for the fix :)

**Pull request merged**
