### PR TITLE
Pre-commit and niv

### PR DESCRIPTION
**Pull request by roberth**
This adds
 - automatic pre-commit hook installation via `nix-shell`
 - a `default.nix` that performs a non-incremental check, for CI
 - pinned nixpkgs

I've used this project to test out `terraform` support in `nix-pre-commit-hooks`. ~It isn't merged yet, so~

TODO

- [x] unblock https://github.com/hercules-ci/nix-pre-commit-hooks/pull/10
- [x] `niv update nix-pre-commit-hooks -b master`
- [ ] either update to terraform 0.12 or make this pr use terraform 0.11
- [ ] re-add the docs updater

### CODE REVIEW

**Comment by zimbatm** [comment]
it looks like it's going in the right direction

**Comment by adrian-gierakowski** [comment]
@roberth looks like cachix/pre-commit-hooks.nix#10 has been merged

**Comment by roberth** [comment]
Updated but still work to do.
- either update to terraform 0.12 or make this pr use terraform 0.11
- re-add the docs updater

**Comment by adrian-gierakowski** [comment]
looks to me that this project already requires terraform 0.12 so no point using 0.11

https://github.com/tweag/terraform-nixos/blob/ee9f768bbe0f6972aced2c02ed96bf076888ba1a/google_image_nixos/versions.tf#L2-L4

I think the problem with terraform-docs is that the version currently used here (0.5.0) is old and does not support 0.12 (the [latest versions](https://github.com/segmentio/terraform-docs/releases/tag/v0.8.2) does)

https://github.com/tweag/terraform-nixos/blob/ee9f768bbe0f6972aced2c02ed96bf076888ba1a/nix/terraform-docs/default.nix#L5

**Comment by zimbatm** [comment]
I think this has been abandoned. Closing for now.

**Pull request closed without merging**
